// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package authiny_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthinyClient is the client API for Authiny service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthinyClient interface {
	// Do the Login
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*CreateApplicationResponse, error)
}

type authinyClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthinyClient(cc grpc.ClientConnInterface) AuthinyClient {
	return &authinyClient{cc}
}

func (c *authinyClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/authiny.Authiny/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authinyClient) CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...grpc.CallOption) (*CreateApplicationResponse, error) {
	out := new(CreateApplicationResponse)
	err := c.cc.Invoke(ctx, "/authiny.Authiny/CreateApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthinyServer is the server API for Authiny service.
// All implementations must embed UnimplementedAuthinyServer
// for forward compatibility
type AuthinyServer interface {
	// Do the Login
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	CreateApplication(context.Context, *CreateApplicationRequest) (*CreateApplicationResponse, error)
	mustEmbedUnimplementedAuthinyServer()
}

// UnimplementedAuthinyServer must be embedded to have forward compatible implementations.
type UnimplementedAuthinyServer struct {
}

func (UnimplementedAuthinyServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthinyServer) CreateApplication(context.Context, *CreateApplicationRequest) (*CreateApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApplication not implemented")
}
func (UnimplementedAuthinyServer) mustEmbedUnimplementedAuthinyServer() {}

// UnsafeAuthinyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthinyServer will
// result in compilation errors.
type UnsafeAuthinyServer interface {
	mustEmbedUnimplementedAuthinyServer()
}

func RegisterAuthinyServer(s grpc.ServiceRegistrar, srv AuthinyServer) {
	s.RegisterService(&Authiny_ServiceDesc, srv)
}

func _Authiny_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthinyServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authiny.Authiny/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthinyServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authiny_CreateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthinyServer).CreateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authiny.Authiny/CreateApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthinyServer).CreateApplication(ctx, req.(*CreateApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authiny_ServiceDesc is the grpc.ServiceDesc for Authiny service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authiny_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authiny.Authiny",
	HandlerType: (*AuthinyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Authiny_Login_Handler,
		},
		{
			MethodName: "CreateApplication",
			Handler:    _Authiny_CreateApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/authiny_grpc/authiny.proto",
}
